### ISSUE TITLE
expand file format support

### ISSUE THREAD

**Issue by akilism** [firstlookmedia/dangerzone-converter#1]
Here are MIME types for Microsoft Office formats: https://filext.com/faq/office_mime_types.html
 
 And for OpenOffice/LibreOffice: https://www.openoffice.org/framework/documentation/mimetypes/mimetypes.html
 
 Dangerzone should support all of these:
 
 * [x]  `.pdf`, `application/pdf`
 * [x]  `.docx`, `application/vnd.openxmlformats-officedocument.wordprocessingml.document`
 * [x]  `.doc`, `application/msword`
 * [x]  `.xlsx`, `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`
 * [x]  `.xls`, `application/vnd.ms-excel`
 * [x]  `.pptx`, `application/vnd.openxmlformats-officedocument.presentationml.presentation`
 * [x]  `.ppt`, `application/vnd.ms-powerpoint`
 * [x]  `.odt`, `application/vnd.oasis.opendocument.text`
 * [x]  `odg`, `application/vnd.oasis.opendocument.graphics`
 * [x]  `odp`, `application/vnd.oasis.opendocument.presentation`
 * [x]  `ops`, `application/vnd.oasis.opendocument.spreadsheet`
 * [x]  `.jpg`, `image/jpeg`
 * [x]  `.gif`, `image/gif`
 * [x]  `.png`, `image/png`
 * [x]  `.tif`, `image/tiff`, `image/x-tiff`

**Comment by micahflee** [comment]
I just added support for all the office document formats. The images should be really simple too -- just need to use ImageMagick's `convert` directly.
